# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  lint:
    docker:
    - image: circleci/node:8.10

    working-directory: ~/ur-web

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

    - run:
        name: Install local dependencies
        command: yarn

    - save_cache:
        key: v1-dependencies-{{ checksum "yarn.lock" }}
        paths:
        - node_modules

    - run:
        name: Linting
        command: yarn lint

  build:
    docker:
    - image: circleci/node:8.10

    working_directory: ~/ur-web

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

    - run:
        name: Building
        command: yarn build --prod

    - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - dist

  doc:
    docker:
    - image: circleci/node:8.10

    working_directory: ~/ur-web

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

    - run:
        name: Generating Documentation
        command: yarn compodoc

    - save_cache:
        key: v1-doc-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - doc

  deploy_app:
    docker:
    - image: circleci/node:8.10

    working_directory: ~/ur-web

    steps:
    - restore_cache:
        keys:
        - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

    - run:
        name: Removing Remote Files
        command: ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST rm -rf /var/www/ur-web/*

    - run:
        name: Deploy Over SSH
        command: rsync -rav ./dist/web/* $SSH_USER@$SSH_HOST:/var/www/ur-web/

  deploy_doc:
    docker:
    - image: circleci/node:8.10

    working_directory: ~/ur-web

    steps:
    - restore_cache:
        keys:
        - v1-doc-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

    - run:
        name: Removing Remote Files
        command: ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST rm -rf /var/www/ur-web/*

    - run:
        name: Deploy Documentation Over SSH
        command: rsync -rav ./doc/* $SSH_USER@$SSH_HOST:/var/www/ur-web/

workflows:
  version: 2

  workflow:
    jobs:
    - lint

    - build:
        requires:
        - lint

    - doc:
        filters:
          branches:
            only: master

    - deploy_app:
        type: approval
        requires:
        - build
        filters:
          branches:
            only: master

    - deploy_doc:
        type: approval
        requires:
        - doc
        filters:
          branches:
            only: master

    - deploy_app_task:
        requires:
        - deploy_app
        filters:
          branches:
            only: master

    - deploy_doc_task:
        requires:
        - deploy_doc
        filters:
          branches:
            only: master
